---
title: Individual thresholds for perceived speed
output: 
  html_document:
    toc: true
    toc_depth: 5
---

```{r global, echo=FALSE,message=FALSE,results='hide'}
source('libsAndMore.R')
opts_chunk$set(echo=FALSE, fig.align='center', fig.width = 10, fig.height = 10)

plotting <- T
```

```{r input, echo=FALSE, message=FALSE, results='hide'}
fitsMatchSpeed <- read.table('logdata/fitsMatchSpeed.txt')
fitsMatchFreq <- read.table('logdata/fitsMatchFreq.txt')

fitsBootExtrDif <- read.table('logdata/fitsBootExtrDif.txt')
fitsBootExtrDif2 <- read.table('logdata/fitsBootExtrDif2.txt')
fitsBootExtrDifNumber <- read.table('logdata/fitsBootExtrDifNumber.txt')
fitsBootExtrDifNumber2 <- read.table('logdata/fitsBootExtrDifNumber2.txt')

fitsBootExtrDifFreq <- read.table('logdata/fitsBootExtrDifFreq.txt')
fitsBootExtrDif2Freq <- read.table('logdata/fitsBootExtrDif2Freq.txt')
fitsBootExtrDifNumberFreq <- read.table('logdata/fitsBootExtrDifNumberFreq.txt')
fitsBootExtrDifNumber2Freq <- read.table('logdata/fitsBootExtrDifNumber2Freq.txt')

fitsBootExtrDifTf <- read.table('logdata/fitsBootExtrDifTf.txt')
fitsBootExtrDif2Tf <- read.table('logdata/fitsBootExtrDif2Tf.txt')
fitsBootExtrDifNumberTf <- read.table('logdata/fitsBootExtrDifNumberTf.txt')
fitsBootExtrDifNumber2Tf <- read.table('logdata/fitsBootExtrDifNumber2Tf.txt')

fitsBootExtrDifSpeedMatch <- 
  read.table('logdata/fitsBootExtrDifSpeedMatch.txt')
fitsBootExtrDif2SpeedMatch <- 
  read.table('logdata/fitsBootExtrDif2SpeedMatch.txt')
fitsBootExtrDifNumberSpeedMatch <- 
  read.table('logdata/fitsBootExtrDifNumberSpeedMatch.txt')
fitsBootExtrDifNumber2SpeedMatch <- 
  read.table('logdata/fitsBootExtrDifNumber2SpeedMatch.txt')

fitsExtr <- read.table('logdata/fitsExtr.txt')
fitsExtrFreq <- read.table('logdata/fitsExtrFreq.txt')
fitsExtrSpeedMatch <- read.table('logdata/fitsExtrSpeedMatch.txt')
```


#### For number and radius

```{r thresholds, message=FALSE, warning=FALSE,fig.height = 20}
plotThresholdsSpeedSpeedMatch <- fitsMatchSpeed %>% group_by(subject) %>% 
  do(plot = plotThreshold2(., NULL, NULL, x = 'speed', 
                          y = 'pse', ymin = 'psemin', ymax = 'psemax',
                          cond = 'numberradius',p))

plotThresholdsFreqSpeedMatch <- fitsMatchSpeed %>% group_by(subject) %>% 
  do(plot = plotThreshold2(., NULL, NULL,x = 'freq', 
                          y = 'pse', ymin = 'psemin', ymax = 'psemax',
                          cond = 'numberradius',p))

plotThresholdsTfSpeedMatch <- fitsMatchSpeed %>% group_by(subject) %>% 
  do(plot = plotThreshold2(., NULL, NULL, x = 'tf', 
                          y = 'pse', ymin = 'psemin', ymax = 'psemax',
                          cond = 'numberradius',p))

plotThresholdsSpeedMatchSpeedMatch <- fitsMatchSpeed %>% group_by(subject) %>% 
  do(plot = plotThreshold2(., NULL, NULL, x = 'speedMatch', 
                          y = 'pse', ymin = 'psemin', ymax = 'psemax',
                          cond = 'numberradius',p))

if (plotting) {
  multiplot(c(plotThresholdsSpeedSpeedMatch$plot,
            plotThresholdsFreqSpeedMatch$plot,
            plotThresholdsTfSpeedMatch$plot,
            plotThresholdsSpeedMatchSpeedMatch$plot),cols=4)
  }
```

#### For radius
```{r thresholdsRadius, message=FALSE, warning=FALSE}
plotThresholdsSpeedRadiusSpeedMatch <- fitsMatchSpeed %>% group_by(subject) %>% 
  do(plot = plotThreshold(., 
                    merge(filter(fitsExtr, radius==4), fitsBootExtrDif), 
                    merge(filter(fitsExtr, radius==4), fitsBootExtrDif2), 
                    x = 'speed', 
                          y = 'pse', ymin = 'psemin', ymax = 'psemax',
                          cond = 'radius',p, all=F))

plotThresholdsFreqRadiusSpeedMatch <- fitsMatchSpeed %>% group_by(subject) %>% 
  do(plot = plotThreshold(., 
                    merge(filter(fitsExtrFreq, radius==4), fitsBootExtrDifFreq), 
                    merge(filter(fitsExtrFreq, radius==4), fitsBootExtrDif2Freq),                     
                          x = 'freq', 
                          y = 'pse', ymin = 'psemin', ymax = 'psemax',
                          cond = 'radius',p,all=F))

plotThresholdsTfRadiusSpeedMatch <- fitsMatchSpeed %>% group_by(subject) %>% 
  do(plot = plotThreshold2(., fitsBootExtrDifTf, fitsBootExtrDif2Tf, x = 'tf', 
                          y = 'pse', ymin = 'psemin', ymax = 'psemax',
                          cond = 'radius',p,all=F))

plotThresholdsSpeedMatchRadiusSpeedMatch <- fitsMatchSpeed %>% group_by(subject) %>% 
  do(plot = plotThreshold(., 
                merge(filter(fitsExtrSpeedMatch, radius==4), fitsBootExtrDifSpeedMatch), 
                merge(filter(fitsExtrSpeedMatch, radius==4), fitsBootExtrDif2SpeedMatch),  
                          x = 'speedMatch', 
                          y = 'pse', ymin = 'psemin', ymax = 'psemax',
                          cond = 'radius',p, all=F))

if (plotting) {
  multiplot(c(plotThresholdsSpeedRadiusSpeedMatch$plot,
            plotThresholdsFreqRadiusSpeedMatch$plot,
            plotThresholdsTfRadiusSpeedMatch$plot,
            plotThresholdsSpeedMatchRadiusSpeedMatch$plot),cols=4)
  }
```


#### For number 
```{r thresholdsNumber, message=FALSE, warning=FALSE}

plotThresholdsSpeedNumberSpeedMatch <- fitsMatchSpeed %>% group_by(subject) %>% 
  do(plot = plotThreshold2(., fitsBootExtrDifNumber, fitsBootExtrDifNumber2,
                          x = 'speed', 
                          y = 'pse', ymin = 'psemin', ymax = 'psemax',
                          cond = 'number',p, all=F))

plotThresholdsFreqNumberSpeedMatch <- fitsMatchSpeed %>% group_by(subject) %>% 
  do(plot = plotThreshold2(., 
                          fitsBootExtrDifNumberFreq, fitsBootExtrDifNumber2Freq, 
                          x = 'freq', 
                          y = 'pse', ymin = 'psemin', ymax = 'psemax',
                          cond = 'number',p, all=F))

plotThresholdsTfNumberSpeedMatch <- fitsMatchSpeed %>% group_by(subject) %>% 
  do(plot = plotThreshold2(., fitsBootExtrDifNumberTf, fitsBootExtrDifNumber2Tf, 
                          x = 'tf', 
                          y = 'pse', ymin = 'psemin', ymax = 'psemax',
                          cond = 'number',p, all=F))

plotThresholdsSpeedMatchNumberSpeedMatch <- fitsMatchSpeed %>% group_by(subject) %>% 
  do(plot = plotThreshold2(., fitsBootExtrDifNumberSpeedMatch, 
                          fitsBootExtrDifNumber2SpeedMatch, x = 'speedMatch', 
                          y = 'pse', ymin = 'psemin', ymax = 'psemax',
                          cond = 'number',p, all=F))

if (plotting) {
  multiplot(c(plotThresholdsSpeedNumberSpeedMatch$plot,
            plotThresholdsFreqNumberSpeedMatch$plot,
            plotThresholdsTfNumberSpeedMatch$plot,
            plotThresholdsSpeedMatchNumberSpeedMatch$plot),cols=4)
  }
```
